/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ApplicationContextClassLoaderParentUnnamedModuleClassLoaderDefinedPackages { 
    name?: string;
    annotations?: Array<object>;
    declaredAnnotations?: Array<object>;
    sealed?: boolean;
    specificationTitle?: string;
    specificationVersion?: string;
    specificationVendor?: string;
    implementationTitle?: string;
    implementationVersion?: string;
    implementationVendor?: string;
}

