/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ApplicationContextClassLoaderParentUnnamedModuleDescriptor } from './application-context-class-loader-parent-unnamed-module-descriptor';
import { ApplicationContextClassLoaderParentUnnamedModuleClassLoader } from './application-context-class-loader-parent-unnamed-module-class-loader';


export interface ApplicationContextClassLoaderParentUnnamedModule { 
    name?: string;
    classLoader?: ApplicationContextClassLoaderParentUnnamedModuleClassLoader;
    descriptor?: ApplicationContextClassLoaderParentUnnamedModuleDescriptor;
    named?: boolean;
    annotations?: Array<object>;
    declaredAnnotations?: Array<object>;
    packages?: Set<string>;
    layer?: object;
}

