/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { RedirectViewServletContext } from './redirect-view-servlet-context';
import { ApplicationContext } from './application-context';


export interface RedirectView { 
    applicationContext?: ApplicationContext;
    servletContext?: RedirectViewServletContext;
    contentType?: string;
    requestContextAttribute?: string;
    staticAttributes?: { [key: string]: object; };
    exposePathVariables?: boolean;
    exposeContextBeansAsAttributes?: boolean;
    exposedContextBeanNames?: Array<string>;
    beanName?: string;
    url?: string;
    contextRelative?: boolean;
    http10Compatible?: boolean;
    exposeModelAttributes?: boolean;
    encodingScheme?: string;
    statusCode?: RedirectView.StatusCodeEnum;
    expandUriTemplateVariables?: boolean;
    propagateQueryParams?: boolean;
    hosts?: Array<string>;
    redirectView?: boolean;
    propagateQueryProperties?: boolean;
    attributes?: { [key: string]: string; };
    attributesMap?: { [key: string]: object; };
    attributesCSV?: string;
}
export namespace RedirectView {
    export type StatusCodeEnum = '100 CONTINUE' | '101 SWITCHING_PROTOCOLS' | '102 PROCESSING' | '103 CHECKPOINT' | '200 OK' | '201 CREATED' | '202 ACCEPTED' | '203 NON_AUTHORITATIVE_INFORMATION' | '204 NO_CONTENT' | '205 RESET_CONTENT' | '206 PARTIAL_CONTENT' | '207 MULTI_STATUS' | '208 ALREADY_REPORTED' | '226 IM_USED' | '300 MULTIPLE_CHOICES' | '301 MOVED_PERMANENTLY' | '302 FOUND' | '302 MOVED_TEMPORARILY' | '303 SEE_OTHER' | '304 NOT_MODIFIED' | '305 USE_PROXY' | '307 TEMPORARY_REDIRECT' | '308 PERMANENT_REDIRECT' | '400 BAD_REQUEST' | '401 UNAUTHORIZED' | '402 PAYMENT_REQUIRED' | '403 FORBIDDEN' | '404 NOT_FOUND' | '405 METHOD_NOT_ALLOWED' | '406 NOT_ACCEPTABLE' | '407 PROXY_AUTHENTICATION_REQUIRED' | '408 REQUEST_TIMEOUT' | '409 CONFLICT' | '410 GONE' | '411 LENGTH_REQUIRED' | '412 PRECONDITION_FAILED' | '413 PAYLOAD_TOO_LARGE' | '413 REQUEST_ENTITY_TOO_LARGE' | '414 URI_TOO_LONG' | '414 REQUEST_URI_TOO_LONG' | '415 UNSUPPORTED_MEDIA_TYPE' | '416 REQUESTED_RANGE_NOT_SATISFIABLE' | '417 EXPECTATION_FAILED' | '418 I_AM_A_TEAPOT' | '419 INSUFFICIENT_SPACE_ON_RESOURCE' | '420 METHOD_FAILURE' | '421 DESTINATION_LOCKED' | '422 UNPROCESSABLE_ENTITY' | '423 LOCKED' | '424 FAILED_DEPENDENCY' | '425 TOO_EARLY' | '426 UPGRADE_REQUIRED' | '428 PRECONDITION_REQUIRED' | '429 TOO_MANY_REQUESTS' | '431 REQUEST_HEADER_FIELDS_TOO_LARGE' | '451 UNAVAILABLE_FOR_LEGAL_REASONS' | '500 INTERNAL_SERVER_ERROR' | '501 NOT_IMPLEMENTED' | '502 BAD_GATEWAY' | '503 SERVICE_UNAVAILABLE' | '504 GATEWAY_TIMEOUT' | '505 HTTP_VERSION_NOT_SUPPORTED' | '506 VARIANT_ALSO_NEGOTIATES' | '507 INSUFFICIENT_STORAGE' | '508 LOOP_DETECTED' | '509 BANDWIDTH_LIMIT_EXCEEDED' | '510 NOT_EXTENDED' | '511 NETWORK_AUTHENTICATION_REQUIRED';
    export const StatusCodeEnum = {
        _100Continue: '100 CONTINUE' as StatusCodeEnum,
        _101SwitchingProtocols: '101 SWITCHING_PROTOCOLS' as StatusCodeEnum,
        _102Processing: '102 PROCESSING' as StatusCodeEnum,
        _103Checkpoint: '103 CHECKPOINT' as StatusCodeEnum,
        _200Ok: '200 OK' as StatusCodeEnum,
        _201Created: '201 CREATED' as StatusCodeEnum,
        _202Accepted: '202 ACCEPTED' as StatusCodeEnum,
        _203NonAuthoritativeInformation: '203 NON_AUTHORITATIVE_INFORMATION' as StatusCodeEnum,
        _204NoContent: '204 NO_CONTENT' as StatusCodeEnum,
        _205ResetContent: '205 RESET_CONTENT' as StatusCodeEnum,
        _206PartialContent: '206 PARTIAL_CONTENT' as StatusCodeEnum,
        _207MultiStatus: '207 MULTI_STATUS' as StatusCodeEnum,
        _208AlreadyReported: '208 ALREADY_REPORTED' as StatusCodeEnum,
        _226ImUsed: '226 IM_USED' as StatusCodeEnum,
        _300MultipleChoices: '300 MULTIPLE_CHOICES' as StatusCodeEnum,
        _301MovedPermanently: '301 MOVED_PERMANENTLY' as StatusCodeEnum,
        _302Found: '302 FOUND' as StatusCodeEnum,
        _302MovedTemporarily: '302 MOVED_TEMPORARILY' as StatusCodeEnum,
        _303SeeOther: '303 SEE_OTHER' as StatusCodeEnum,
        _304NotModified: '304 NOT_MODIFIED' as StatusCodeEnum,
        _305UseProxy: '305 USE_PROXY' as StatusCodeEnum,
        _307TemporaryRedirect: '307 TEMPORARY_REDIRECT' as StatusCodeEnum,
        _308PermanentRedirect: '308 PERMANENT_REDIRECT' as StatusCodeEnum,
        _400BadRequest: '400 BAD_REQUEST' as StatusCodeEnum,
        _401Unauthorized: '401 UNAUTHORIZED' as StatusCodeEnum,
        _402PaymentRequired: '402 PAYMENT_REQUIRED' as StatusCodeEnum,
        _403Forbidden: '403 FORBIDDEN' as StatusCodeEnum,
        _404NotFound: '404 NOT_FOUND' as StatusCodeEnum,
        _405MethodNotAllowed: '405 METHOD_NOT_ALLOWED' as StatusCodeEnum,
        _406NotAcceptable: '406 NOT_ACCEPTABLE' as StatusCodeEnum,
        _407ProxyAuthenticationRequired: '407 PROXY_AUTHENTICATION_REQUIRED' as StatusCodeEnum,
        _408RequestTimeout: '408 REQUEST_TIMEOUT' as StatusCodeEnum,
        _409Conflict: '409 CONFLICT' as StatusCodeEnum,
        _410Gone: '410 GONE' as StatusCodeEnum,
        _411LengthRequired: '411 LENGTH_REQUIRED' as StatusCodeEnum,
        _412PreconditionFailed: '412 PRECONDITION_FAILED' as StatusCodeEnum,
        _413PayloadTooLarge: '413 PAYLOAD_TOO_LARGE' as StatusCodeEnum,
        _413RequestEntityTooLarge: '413 REQUEST_ENTITY_TOO_LARGE' as StatusCodeEnum,
        _414UriTooLong: '414 URI_TOO_LONG' as StatusCodeEnum,
        _414RequestUriTooLong: '414 REQUEST_URI_TOO_LONG' as StatusCodeEnum,
        _415UnsupportedMediaType: '415 UNSUPPORTED_MEDIA_TYPE' as StatusCodeEnum,
        _416RequestedRangeNotSatisfiable: '416 REQUESTED_RANGE_NOT_SATISFIABLE' as StatusCodeEnum,
        _417ExpectationFailed: '417 EXPECTATION_FAILED' as StatusCodeEnum,
        _418IAmATeapot: '418 I_AM_A_TEAPOT' as StatusCodeEnum,
        _419InsufficientSpaceOnResource: '419 INSUFFICIENT_SPACE_ON_RESOURCE' as StatusCodeEnum,
        _420MethodFailure: '420 METHOD_FAILURE' as StatusCodeEnum,
        _421DestinationLocked: '421 DESTINATION_LOCKED' as StatusCodeEnum,
        _422UnprocessableEntity: '422 UNPROCESSABLE_ENTITY' as StatusCodeEnum,
        _423Locked: '423 LOCKED' as StatusCodeEnum,
        _424FailedDependency: '424 FAILED_DEPENDENCY' as StatusCodeEnum,
        _425TooEarly: '425 TOO_EARLY' as StatusCodeEnum,
        _426UpgradeRequired: '426 UPGRADE_REQUIRED' as StatusCodeEnum,
        _428PreconditionRequired: '428 PRECONDITION_REQUIRED' as StatusCodeEnum,
        _429TooManyRequests: '429 TOO_MANY_REQUESTS' as StatusCodeEnum,
        _431RequestHeaderFieldsTooLarge: '431 REQUEST_HEADER_FIELDS_TOO_LARGE' as StatusCodeEnum,
        _451UnavailableForLegalReasons: '451 UNAVAILABLE_FOR_LEGAL_REASONS' as StatusCodeEnum,
        _500InternalServerError: '500 INTERNAL_SERVER_ERROR' as StatusCodeEnum,
        _501NotImplemented: '501 NOT_IMPLEMENTED' as StatusCodeEnum,
        _502BadGateway: '502 BAD_GATEWAY' as StatusCodeEnum,
        _503ServiceUnavailable: '503 SERVICE_UNAVAILABLE' as StatusCodeEnum,
        _504GatewayTimeout: '504 GATEWAY_TIMEOUT' as StatusCodeEnum,
        _505HttpVersionNotSupported: '505 HTTP_VERSION_NOT_SUPPORTED' as StatusCodeEnum,
        _506VariantAlsoNegotiates: '506 VARIANT_ALSO_NEGOTIATES' as StatusCodeEnum,
        _507InsufficientStorage: '507 INSUFFICIENT_STORAGE' as StatusCodeEnum,
        _508LoopDetected: '508 LOOP_DETECTED' as StatusCodeEnum,
        _509BandwidthLimitExceeded: '509 BANDWIDTH_LIMIT_EXCEEDED' as StatusCodeEnum,
        _510NotExtended: '510 NOT_EXTENDED' as StatusCodeEnum,
        _511NetworkAuthenticationRequired: '511 NETWORK_AUTHENTICATION_REQUIRED' as StatusCodeEnum
    };
}


