/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ApplicationContextClassLoaderParentUnnamedModuleClassLoader } from './application-context-class-loader-parent-unnamed-module-class-loader';
import { RedirectViewServletContextFilterRegistrations } from './redirect-view-servlet-context-filter-registrations';
import { RedirectViewServletContextJspConfigDescriptor } from './redirect-view-servlet-context-jsp-config-descriptor';
import { RedirectViewServletContextSessionCookieConfig } from './redirect-view-servlet-context-session-cookie-config';
import { RedirectViewServletContextServletRegistrations } from './redirect-view-servlet-context-servlet-registrations';


export interface RedirectViewServletContext { 
    classLoader?: ApplicationContextClassLoaderParentUnnamedModuleClassLoader;
    majorVersion?: number;
    minorVersion?: number;
    contextPath?: string;
    attributeNames?: object;
    initParameterNames?: object;
    sessionTrackingModes?: Set<RedirectViewServletContext.SessionTrackingModesEnum>;
    sessionTimeout?: number;
    servletNames?: object;
    servletContextName?: string;
    jspConfigDescriptor?: RedirectViewServletContextJspConfigDescriptor;
    responseCharacterEncoding?: string;
    sessionCookieConfig?: RedirectViewServletContextSessionCookieConfig;
    requestCharacterEncoding?: string;
    filterRegistrations?: { [key: string]: RedirectViewServletContextFilterRegistrations; };
    effectiveSessionTrackingModes?: Set<RedirectViewServletContext.EffectiveSessionTrackingModesEnum>;
    effectiveMajorVersion?: number;
    defaultSessionTrackingModes?: Set<RedirectViewServletContext.DefaultSessionTrackingModesEnum>;
    effectiveMinorVersion?: number;
    servletRegistrations?: { [key: string]: RedirectViewServletContextServletRegistrations; };
    virtualServerName?: string;
    serverInfo?: string;
    servlets?: object;
}
export namespace RedirectViewServletContext {
    export type SessionTrackingModesEnum = 'COOKIE' | 'URL' | 'SSL';
    export const SessionTrackingModesEnum = {
        Cookie: 'COOKIE' as SessionTrackingModesEnum,
        Url: 'URL' as SessionTrackingModesEnum,
        Ssl: 'SSL' as SessionTrackingModesEnum
    };
    export type EffectiveSessionTrackingModesEnum = 'COOKIE' | 'URL' | 'SSL';
    export const EffectiveSessionTrackingModesEnum = {
        Cookie: 'COOKIE' as EffectiveSessionTrackingModesEnum,
        Url: 'URL' as EffectiveSessionTrackingModesEnum,
        Ssl: 'SSL' as EffectiveSessionTrackingModesEnum
    };
    export type DefaultSessionTrackingModesEnum = 'COOKIE' | 'URL' | 'SSL';
    export const DefaultSessionTrackingModesEnum = {
        Cookie: 'COOKIE' as DefaultSessionTrackingModesEnum,
        Url: 'URL' as DefaultSessionTrackingModesEnum,
        Ssl: 'SSL' as DefaultSessionTrackingModesEnum
    };
}


