/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ViewDTO } from './view-dto';
import { ClickDTO } from './click-dto';


export interface StatsDTO { 
    views?: Array<ViewDTO>;
    clicks?: Array<ClickDTO>;
}

